logger:
  level: "INFO"
  http_log_file: "logs/http.log"

server:
  host: "localhost"
  port: "8082"

database:
  dsn: "postgres://calendar:calendar@localhost:5432/calendar?sslmode=disable"

storage:
  type: "memory"  # "memory" или "sql"
