logger:
  level: "INFO"

database:
  dsn: "postgres://calendar:calendar@postgres:5432/calendar?sslmode=disable"

storage:
  type: "sql"

kafka:
  brokers:
    - "kafka:9092"
  topic: "calendar-notifications"
  group_id: "calendar-storer-group"
